on:
  push:
    branches:
      - migrate-to-gh-actions
      - master

name: bookdown

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc and pandoc citeproc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'


      - name: Build HTML
        run: Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"

      - name: Build PDF
        run: Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"

      - name: Build eBook
        run: Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"
